version: '3.1'

services:

  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=lucky_louis
      - POSTGRES_DB=dn7

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080